### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wicivo** [ceeden/betterblockentities#1]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/603e0a80-e8f0-4dbb-824b-4b70a4d9101e" />

**Comment by wicivo** [comment]
https://streamable.com/3pz30n

**Comment by wicivo** [comment]
without mod 

<img width="1920" height="991" alt="Image" src="https://github.com/user-attachments/assets/2e63fd64-3772-459e-a4cf-f1438760bcc3" />

**Comment by ceeden** [comment]
@wicivo I have now pushed support for all the new copper chests, and fixed the double chest UV mappings for all chest variants. Pushes was made for 1.21.9, 1.21.8 will be updated shortly. As for the little "glitch" you see when you open and close a chest or any other supported Block Entity is a lighting bug, lighting is computed differently for meshed blocks and "BER" blocks, I'm on it though. Bells are still bugged as they require a Mixin into it's "BER" renderer to add the posts, bar, etc... so that gets rendered when the block animates and not just the bell itself.

**Comment by ceeden** [comment]
> Sorry for the inconvenience prior, but how does one exactly go about getting a working file for this mod? I want to get a 1.21.6 version running, but I don't know exactly what I need to do to get that point, since, I've tried navigating throughout this repository and there are no releases, and I'm not sure where else to look for files, sorry for the noobiness.

The 1.21.8 branch is compatible all the way down to 1.21.6. Just change the gradle files to match your minecraft version and compile the gradle project

**Comment by ceeden** [comment]
> Also some signs are invisible

Could you please attach a picture or a video, and as much details as possible (MC version, what type of signs, etc...) so i can try to replicate it

**Comment by EGOIST1372** [comment]
> [@wicivo](https://github.com/wicivo) I have now pushed support for all the new copper chests, and fixed the double chest UV mappings for all chest variants. Pushes was made for 1.21.9, 1.21.8 will be updated shortly. As for the little "glitch" you see when you open and close a chest or any other supported Block Entity is a lighting bug, lighting is computed differently for meshed blocks and "BER" blocks, I'm on it though. Bells are still bugged as they require a Mixin into it's "BER" renderer to add the posts, bar, etc... so that gets rendered when the block animates and not just the bell itself.

It be great either reopen the issue so new users dont open duplicate issues
since bells still bugged and the initial bug was for bells so it shouldnt be closed IMO
also it be great you create an issue list (current bugs that need fixing like light block renderer)

**Comment by derpfriend** [comment]
im still struggling to build this, is there a tutorial i could be pointed to? the farthest ive gotten is finding a (singular) gradle file i could open in notepad and changed those to match the versions i needed, or if any others out there have already forked a 1.21.6 version, if i could be pointed to your direction aswell. Thank you very much

**Comment by ceeden** [comment]
Bells are now fixed and renders fine (except for the lighting bug that is currently present on all supported blocks) The lighting bug needs some time with the thinking cap, I need to come up with a cleaver and minimalistic solution. The repo will be update shortly :)
https://www.youtube.com/watch?v=n4qnOsyARNE

**Comment by ceeden** [comment]
> im still struggling to build this, is there a tutorial i could be pointed to? the farthest ive gotten is finding a (singular) gradle file i could open in notepad and changed those to match the versions i needed, or if any others out there have already forked a 1.21.6 version, if i could be pointed to your direction aswell. Thank you very much

I suggest waiting for a official release if you do not have any modding/java experience. If you really want to build this project just look up any tutorial on YouTube for Fabric modding. You need a IDE (IntelliJ by JetBrains is the most common one for Java I would say)

**Comment by EGOIST1372** [comment]
> Bells are now fixed and renders fine (except for the lighting bug that is currently present on all supported blocks) The lighting bug needs some time with the thinking cap, I need to come up with a cleaver and minimalistic solution. The repo will be updated shortly :) https://www.youtube.com/watch?v=n4qnOsyARNE

can you push the changes to github? seems there is no changes since october 4

**Comment by EGOIST1372** [comment]
> im still struggling to build this, is there a tutorial i could be pointed to? the farthest ive gotten is finding a (singular) gradle file i could open in notepad and changed those to match the versions i needed, or if any others out there have already forked a 1.21.6 version, if i could be pointed to your direction aswell. Thank you very much

click on link below
https://github.com/ShadowTigerCool/betterblockentities/actions/runs/18245357111
scroll down the page
hit on artifacts link
it will download a zip file
in it there is a sources and a normal jar file
you just need the normal one
you take it out of the zip file and paste it into your mods folder
THEN (this step is important)
right click on jar file
hit open with Winrar (everyone have winrar app in their computer and I hope you have one as well)
then click and open on the fabric.mod.json file
It should automatically open it in notepad or asks to open with notepad
do it and then scroll until you see the  "minecraft": ">=1.21.8"
change the version to 1.21.6
and do control+S and it will save the file
but at same time winrar asks the following message, you just hit yes

<img width="2383" height="1282" alt="Image" src="https://github.com/user-attachments/assets/748621d2-7ef0-47c4-8c4e-c4da3243bfbd" />

Voila you got a working 1.21.6 version
Enjoy

**Comment by derpfriend** [comment]
thank you so much for the guide, unfortunately im still not able to get it work, despite changing the minecraft versions, and i also did an attempt to change the fabric loader and api versions as well. My client just kept crashing and giving me Exit error code -1, I shall wait for an official release. 

<img width="449" height="150" alt="Image" src="https://github.com/user-attachments/assets/8e32ecfc-e5a3-4f6d-abae-7c30b8541571" />

**Comment by derpfriend** [comment]
sodium-fabric-0.7.0+mc1.21.8 (this is the most recent version on modrinth that includes 1.21.6, its displayed as 1.21.6-1.21.8) & modmenu-15.0.0

**Comment by derpfriend** [comment]
no success, even after a few different variations, thank you for your effort tho, for reference, i downloaded the api you sent me, changed a few version related things where i saw 1.21.8, but no avail, if you still want to try assist me id love to move over to discord (brandonkoga) just to not continuously spam this thread, but no worries if not, i do appreciate all the assistance you have already shown me, thank you again.

**Comment by ceeden** [comment]
@EGOIST1372 bell fix/commits are pushed (for 1.21.9)

**Comment by EGOIST1372** [comment]
> [@EGOIST1372](https://github.com/EGOIST1372) bell fix/commits are pushed (for 1.21.9)

tnx then ig this issue can be closed
new issue is interesting #2

**Comment by EGOIST1372** [comment]
> > > [@EGOIST1372](https://github.com/EGOIST1372) bell fix/commits are pushed (for 1.21.9)
> > 
> > 
> > tnx then ig this issue can be closed new issue is interesting [#2](https://github.com/ceeden/betterblockentities/issues/2)
> 
> just fixed it, the issue was the block pos was still in the animation map when broken so the next block didn´t want to render. a simple sanity check was added.

Great news, that was fast :D
also the issue that our friend had with error code -1 was sodium 0.7 wasnt compatible with BBE
so after he downgrade to 0.6.13 it worked with my cheaty method
but now i asked him to open a new issue with logs so u can fix it
